title: Gysinge Bryggeri
instagram: https://instagram.com/gysingebryggeri
facebook: https://facebook.com/gysingebryggeri
facebook_club: https://facebook.com/gysingebryggerisallskap
email: info@gysingebryggeri.se
address:
    street: Kölnavägen 27
    postal_code: 811 97
    city: Gysinge
bookings:
    beer_tasting:
        subject: Bokning av ölprovning
    beer_brewing:
        subject: Bokning av medlemsbryggning
